dataset:
  train:
    local:
      data_root: C:\\Users\\ipmstud\\Desktop\\mlschool\\OMGEmotionChallenge/omg_TrainVideos/frames #D:\AVER\AFEW-VA\crop
      file_list: C:\\Users\\ipmstud\\Desktop\\mlschool\\omg_TrainVideos/train_data_with_landmarks.txt
    server:
      data_root: /media/stc_ml_school/data/OMGEmotionChallenge/omg_TrainVideos/frames #D:\AVER\AFEW-VA\crop
      file_list: /media/stc_ml_school/data/OMGEmotionChallenge/omg_TrainVideos/train_data_with_landmarks.txt
  valid:
    local:
      data_root: C:\\Users\\ipmstud\\Desktop\\mlschool\\OMGEmotionChallenge/omg_ValidVideos/frames #D:\AVER\AFEW-VA\crop
      file_list: C:\\Users\\ipmstud\\Desktop\\mlschool\\OMGEmotionChallenge/omg_ValidVideos/valid_data_with_landmarks.txt #D:\AVER\AFEW-VA\crop/test_data_with_landmarks.txt
    server:
      data_root: /media/stc_ml_school/data/OMGEmotionChallenge/omg_ValidVideos/frames #D:\AVER\AFEW-VA\crop
      file_list: /media/stc_ml_school/data/OMGEmotionChallenge/omg_ValidVideos/valid_data_with_landmarks.txt #D:\AVER\AFEW-VA\crop/test_data_with_landmarks.txt

seed: 1234

net:
  type: GRUNet #ResNet
  depth: 6
  imsize: (256,256)
  softmax_size: 2
  fine_tune: no


parser:
  max_num_clips: 10
  max_num_samples: 0

preproc:
  data_frame:
    width: 256
    height: 256
    depth: 5
  is_color: True
  mean: 127.5
  scale: 0.007843
  extend_size: 300
  crop_size: 224
  aug:
    pad: 0
    color: BGR
    use_cutout: False
    use_mirroring: True
    use_random_crop: False
    use_center_crop: False
    use_random_gray: True

sampler:
  samples_is_randomize: no
  step_size_for_samples: 6

train_batcher:
  batch: 256 #batch size
  queue_size: 5
  disk_reader_process_num: 1

valid_batcher:
  batch: 256 #batch size
  queue_size: 5
  disk_reader_process_num: 1

batch_proc:
  use_pin_memory: yes
  use_async: yes

opt:
  type: Adam
  lr: 0.006 #initial learning rate
  momentum: 0.2
  weight_decay: 5.e-4 #initial weight decay

lr_scheduler:
  type: SGDR #MultiCyclePolicy #, LRFinder, OneCyclePolicy
  gamma: 0.1
  use_linear_decay: yes
  scale_lr: [1., 1]
  scale_lr_fc: [1., 1]

train:
  cuda_device: 0 #cuda device id
  step_size: 100 #lr scheduler step size
  step_print: 100
  epoch_size: 100000 #epoch size
  max_iter: 10000000 #maximum iteration for training
  validate_iter: 1000
  snapshot_iter: 10000 #snapshot model frequency
  experiment_name: 'EmoV0_step0' #name for current experiment

losses:
   MSE:
    w: 1.

ini_net:
  local:  C:\\Users\\ipmstud\\Desktop\\mlschool\\log\\VEmotionNet\\EmoV1_step1\\EmoV0_step0_iter_0.model
  server: /media/stc_ml_school/team1/logs/VEmotionNet/EmoV0_step0_iter_0.model

logging:
  log_dir:
    local:  C:\\Users\\ipmstud\\Desktop\\mlschool\\logs
    server: /media/stc_ml_school/team1/logs
  tb_log_dir:
    local:  C:\\Users\\ipmstud\\Desktop\\mlschool\\logs
    server: /media/stc_ml_school/team1/logs
  snapshot_dir:
    local: C:\\Users\\ipmstud\\Desktop\\mlschool\\logs
    server: /media/stc_ml_school/team1/logs

test:
  dataset:
    data_root:
      local:  D:\AVER\AFEW-VA\crop
      server: /media/data/stc-85k-a/faces
    test_file_list:
      local: D:\AVER\AFEW-VA\crop/test_data_with_landmarks.txt
      server: /media/data/kalinovskiy/train_file_list_85k.txt

  cuda_device: 0
  file_model: C:\\Users\\ipmstud\\Desktop\\mlschool\\logs\\EmoV0_step0\EmoV0_step0_iter_25000.model
